/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=config/wrangler-types.empty --include-runtime=false --strict-vars=false --env-interface=WorkerEnv worker-env.d.ts` (hash: 4d9b341e71f8a6412163afa8eb5064e5)
interface __BaseEnv_WorkerEnv {
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	GENERATION_QUEUE: Queue;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	AUTH_MODE: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	ACCESS_AUTO_PROVISION: string;
	REGISTRATION_MODE: string;
	GENERATION_MODE: string;
	AGENT_MODE: string;
	ASSISTED_PROVIDER: string;
	ASSISTED_DATA_POLICY: string;
	ASSISTED_EVALUATION: string;
	ASSISTED_BUDGET_MODE: string;
	MAX_ACTIVE_GENERATIONS_PER_WORKSPACE: string;
	CAMPAIGN_AGENT: DurableObjectNamespace<import("./src/worker").CampaignAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "CampaignAgent";
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "AUTH_MODE" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ACCESS_AUTO_PROVISION" | "REGISTRATION_MODE" | "GENERATION_MODE" | "AGENT_MODE" | "ASSISTED_PROVIDER" | "ASSISTED_DATA_POLICY" | "ASSISTED_EVALUATION" | "ASSISTED_BUDGET_MODE" | "MAX_ACTIVE_GENERATIONS_PER_WORKSPACE">> {}
}
