/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=WorkerEnv worker-env.d.ts` (hash: a85e05d0f909857383a9afe49b12ebb3)
interface __BaseEnv_WorkerEnv {
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	GENERATION_QUEUE: Queue;
	APP_ORIGIN: string;
	AUTH_MODE: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	ACCESS_AUTO_PROVISION: string;
	REGISTRATION_MODE: string;
	GENERATION_MODE: string;
	AGENT_MODE: string;
	CAMPAIGN_AGENT: DurableObjectNamespace<import("./src/worker").CampaignAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "CampaignAgent";
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "AUTH_MODE" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ACCESS_AUTO_PROVISION" | "REGISTRATION_MODE" | "GENERATION_MODE" | "AGENT_MODE">> {}
}
